### ISSUE TITLE
async/await for operations

### ISSUE THREAD

**Issue by dlambApLogic** [marosolutions/marketing-dotnet#3]
Search through the code for uses of Async and strip out .Result
E.g., in _BaseApi, line 95,
`apiResponse = HttpClient.SendAsync(request).Result;`
should be
`apiResponse = await HttpClient.SendAsync(request);`

And the function signature should be
`protected async Task<IOperationResult<dynamic>> Get(...)`

This needs to be the case for all uses of async. You will likely end up converting everything to async tasks.

**Comment by santoshshrest** [comment]
all operations such as get, post, put and delete are converted to async methods.
