### ISSUE TITLE
_BaseApi try/catch

### ISSUE THREAD

**Issue by dlambApLogic** [marosolutions/marketing-dotnet#7]
The only line in the `try` body should be the SendAsync command, and it should only attempt to catch HttpExceptions. The command that reads it (`var data = apiResponse....`) should come after the try/catch. We do not want to run the risk of catching exceptions by accident.

**Comment by santoshshrest** [comment]
try catch is added where needed. try catch code block is used in BaseApi class when requesting api and excepts only HttpRequestException
